delete from user_transaction_data;
delete from user_transaction;
delete from problem_reference;
delete from problem;
delete from hearing_part;
delete from session;
delete from availability;
delete from room;
delete from person;