server:
  port: ${SERVER_PORT:8092}

management:
  security:
    enabled: ${MANAGEMENT_SECURITY_ENABLED:true}

liquibase:
  enabled: true
  change-log: classpath:db/db-testdata-changelog.yaml

#If you use a database then uncomment below lines and update db properties accordingly leaving tomcat connection settings unchanged.
spring:
  application:
    name: Scheduling and Listng Events
  datasource:
      url: jdbc:postgresql://${SNL_EVENTS_DB_HOST:localhost}:${SNL_EVENTS_DB_PORT:5432}/${SNL_EVENTS_DB_NAME:snl}${SNL_EVENTS_DB_PARAMS:?}
      username: ${SNL_EVENTS_DB_USERNAME:snluser}
      password: ${SNL_EVENTS_DB_PASSWORD:snlpass}
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
#      properties:
#        charSet: UTF-8
#      tomcat:
#        max-active: 10
#        max-idle: 10
#        min-idle: 2
#        max-wait: 10000
#        test-on-borrow: true
#        test-on-connect: true
#        test-on-idle: true
#        validation-query: "SELECT 1"
#        time-between-eviction-runs-millis: 10000
#        test-while-idle: true
#        test-on-return: true
#        remove-abandoned: true
#        remove-abandoned-timeout: 60
#        log-abandoned: true
#        abandon-when-percentage-full: 0
