server:
  port: 8092

management:
  security:
    enabled: ${MANAGEMENT_SECURITY_ENABLED:true}

liquibase:
  enabled: true
  change-log: classpath:db/db-testdata-changelog.yaml

#If you use a database then uncomment below lines and update db properties accordingly leaving tomcat connection settings unchanged.
spring:
  application:
    name: Spring Boot Template
  datasource:
      url: jdbc:postgresql://${SNL-EVENTS_DB_HOST}:${SNL-EVENTS_DB_PORT}/${SNL-EVENTS_DB_NAME}
      username: ${SNL-EVENTS_DB_USERNAME}
      password: ${SNL-EVENTS_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
#      properties:
#        charSet: UTF-8
#      tomcat:
#        max-active: 10
#        max-idle: 10
#        min-idle: 2
#        max-wait: 10000
#        test-on-borrow: true
#        test-on-connect: true
#        test-on-idle: true
#        validation-query: "SELECT 1"
#        time-between-eviction-runs-millis: 10000
#        test-while-idle: true
#        test-on-return: true
#        remove-abandoned: true
#        remove-abandoned-timeout: 60
#        log-abandoned: true
#        abandon-when-percentage-full: 0
