server:
  port: ${SERVER_PORT:8092}

management:
  security:
    enabled: ${MANAGEMENT_SECURITY_ENABLED:true}
    events:
      jwtSecret: "${SNL_S2S_JWT_SECRET:sialaBabaMak}"
      jwtExpirationInMs: 30000
    rules:
      jwtSecret: "${SNL_S2S_JWT_SECRET:sialaBabaMak}"
      jwtExpirationInMs: 30000


fact-propagation:
  engines:
    - name: Listings
      reloadStatusUrl: ${SNL_RULES_URL:http://localhost:8091}/reload/status?rulesDefinition=Listings
      msgUrl: ${SNL_RULES_URL:http://localhost:8091}/msg?rulesDefinition=Listings
      msgTypes:
        - upsert-year
        - upsert-month
        - upsert-day
        - upsert-hour
        - upsert-minute
        - insert-session
        - upsert-session
        - delete-session
        - insert-hearingPart
        - upsert-hearingPart
        - delete-hearingPart
        - insert-sessionType
        - upsert-sessionType
        - delete-sessionType
    - name: Sessions
      reloadStatusUrl: ${SNL_RULES_URL:http://localhost:8091}/reload/status?rulesDefinition=Sessions
      msgUrl: ${SNL_RULES_URL:http://localhost:8091}/msg?rulesDefinition=Sessions
      msgTypes:
        - upsert-year
        - upsert-month
        - upsert-day
        - upsert-hour
        - upsert-minute
        - insert-session
        - upsert-session
        - delete-session
        - upsert-room
        - upsert-judge

liquibase:
  enabled: ${ENABLE_DB_MIGRATE_IN_SERVICE:true}
  change-log: classpath:db/db-testdata-changelog.yaml

azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:dummy}

#If you use a database then uncomment below lines and update db properties accordingly leaving tomcat connection settings unchanged.
spring:
  application:
    name: SnL Events
  datasource:
      url: jdbc:postgresql://${SNL_EVENTS_DB_HOST:localhost}:${SNL_EVENTS_DB_PORT:5432}/${SNL_EVENTS_DB_NAME:snl}${SNL_EVENTS_DB_PARAMS:?}
      username: ${SNL_EVENTS_DB_USERNAME:snluser}
      password: ${SNL_EVENTS_DB_PASSWORD:snlpass}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
#      properties:
#        charSet: UTF-8
#      tomcat:
#        max-active: 10
#        max-idle: 10
#        min-idle: 2
#        max-wait: 10000
#        test-on-borrow: true
#        test-on-connect: true
#        test-on-idle: true
#        validation-query: "SELECT 1"
#        time-between-eviction-runs-millis: 10000
#        test-while-idle: true
#        test-on-return: true
#        remove-abandoned: true
#        remove-abandoned-timeout: 60
#        log-abandoned: true
#        abandon-when-percentage-full: 0

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 30000
